apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: SocialMedia
        tier: backend
        track: stable
    spec:
      containers:
        - name: backend
          image: 'estebangarviso/Api.SocialMedia'
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              value: mongo-service
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: SocialMedia
    tier: backend
