apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: SocialMedia
        tier: frontend
        track: stable
    spec:
      containers:
        - name: nginx
          image: 'estebangarviso/Web.SocialMedia'
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
    - port: 8888
      targetPort: 80
  selector:
    app: SocialMedia
    tier: frontend
  type: NodePort
